sources:
  - name: amazon_databricks
    database: amazon
    schema: bronze  
    tables:
      - name: orders
      - name: customers
      - name: products
      - name: order_items
      - name: stores
      - name: employees